Extending auth build to docker

diff --git a/.github/workflows/auth-build.yml b/.github/workflows/auth-build.yml
--- a/.github/workflows/auth-build.yml
+++ b/.github/workflows/auth-build.yml
@@ -26,3 +26,23 @@ jobs:
     - name: Build Auth Service
       working-directory: ./auth
       run: mvn clean install -Drevision=$(git rev-parse --short HEAD)
+
+    - name: Login to Docker Hub
+      if: github.ref == 'refs/heads/trunk'
+      uses: docker/login-action@v3
+      with:
+        username: ${{ secrets.DOCKER_USER }}
+        password: ${{ secrets.DOCKER_TOKEN }}
+
+    - name: Build and Push Docker image
+      if: github.ref == 'refs/heads/trunk'
+      working-directory: ./auth
+      run: |
+        if [ -f target/restful-booker-platform-auth-*-exec.jar ]; then
+          VERSION=$(ls target/restful-booker-platform-auth-*-exec.jar | cut -d '-' -f 5 | cut -c1-11)
+          docker build -t mwinteringham/restfulbookerplatform_auth:$VERSION .
+          docker push mwinteringham/restfulbookerplatform_auth:$VERSION
+        else
+          echo "Auth JAR file not found"
+          exit 1
+        fi
